[build]
  Command = "yarn build"
  Functions = "lambda"
  Publish = "dist"

# # A basic redirect rule
# [[redirects]]
#   from = "/api/restaurants"
#   to = "/.netlify/functions/restaurantList"

#   # By default, redirects won't be applied if there's a file with the same
#   # path as the one defined in the `from` property. Setting `force` to `true`
#   # will make the redirect rule take precedence over any existing files.
#   force = true

# [[redirects]]
#   from = "/api/cities"
#   to = "/.netlify/functions/cityList"
